coMeeting/config/routes.rb
CoMeeting::Application.routes.draw do

	get "meetings/get_admin_circles"
	
	get "meetings/get_minutes"
	
	post "meetings/update_minutes"
	
	post "meetings/update_action_item"
	
	post "participations/send_email" => "participations#send_email", :as => "send_email"

	scope "(:locale)", :locale => /en|pt/ do
		
		get "meetings/:id/confirm" => "participations#confirm", :as => "confirm_participation"
	
		get "meetings/:id/decline" => "participations#decline", :as => "decline_participation"
	
		get "meetings/:id/download_pdf" => "meetings#download_pdf", :as => "download_pdf"
		
		get "about-us" => "static#about_us", :as => "about_us"
	
		resources :meetings
		
		root :to => 'home#index'
	end
	
	match '/:anything' => redirect("/"), :constraints => { :anything => /.*/ }

end

coMeeting/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">

<meta name="keywords" content="meeting scheduler, meeting scheduling, meeting, plan a meeting, meeting, organizer, scheduling, schedule, agenda, timetable, calendar, appointment, date, coordinate, poll, meet, lunch, dinner, workshop, team, weekend, event, invitation, online" />
<meta name="description" content="coMeeting helps scheduling meetings and other appointments. coMeeting is simple, quick, free and requires no registration." />
<meta name="application-name" content="coMeeting" />
<meta name="author" content="coMeeting" />

<title>coMeeting</title>
<%= favicon_link_tag %>

<%= stylesheet_link_tag "web_app_theme" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tag %>

<script>
  $(document).ready(function(){
    $('#main').localScroll({
      target:'body'
    }); 
  });
  
  function toggleDiv(divId) {
    $("#"+divId).slideToggle("slow");
  }
  
  var mouse_is_inside = false;

  $(document).ready(function()
  {
    $('#drop_menu').hover(function(){ 
      mouse_is_inside=true; 
    }, function(){ 
      mouse_is_inside=false; 
    });

    $("body").mouseup(function(){ 
      if(! mouse_is_inside) $('#drop_items').slideUp("slow");
    });
  });
</script>

</head>
<body>
  <div id="container">
    <div id="header">
      <%= link_to image_tag("/assets/comeeting3_small.png", :alt => "", :class => "logo") , root_path %>
      <div id="user-navigation">
        <ul class="wat-cf">
		  <li id="drop_menu">
              <a href="#" onclick="toggleDiv('drop_items');return false;"><%= image_tag("/assets/icons/globe.png", :alt => "") + t("current_language", :default => "English") %></a>
			  <ul id="drop_items">
				<li><%= link_to "English", url_for( :locale => "en" ) %></li>
				<li><%= link_to "Portugu&#234;s".html_safe, url_for( :locale => "pt" ) %></li>
			  </ul>
		  </li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf">
          <li class="first"><%= link_to t("about_us", :default => "About Us"), about_us_path %></li>
        </ul>
      </div>
    </div>
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
      </div>
      <div id="footer">
        <div class="block">
          <p>Copyright &copy; 2011 coMeeting</p>
        </div>
      </div>
    </div>
  </div>
</body>
</html>