coMeeting/config/routes.rb
CoMeeting::Application.routes.draw do

	get "meetings/get_admin_circles"
	
	get "meetings/get_minutes"
	
	post "meetings/update_minutes"
	
	post "meetings/update_action_item"
	
	post "participations/send_email" => "participations#send_email", :as => "send_email"

	scope "(:locale)", :locale => /en|pt/ do
		
		get "meetings/:id/confirm" => "participations#confirm", :as => "confirm_participation"
	
		get "meetings/:id/decline" => "participations#decline", :as => "decline_participation"
	
		get "meetings/:id/download_pdf" => "meetings#download_pdf", :as => "download_pdf"
		
		get "about-us" => "static#about_us", :as => "about_us"
	
		resources :meetings
		
		root :to => 'home#index'
	end
	
	match '/:anything' => redirect("/"), :constraints => { :anything => /.*/ }

end

coMeeting/app/models/meeting.rb
class Meeting < ActiveRecord::Base
  serialize :topics, Array

  validates :subject, :presence => true
  validates :local, :presence => true
  validates :meeting_date, :presence => true

  has_many :participations, :class_name => "Participation"
  has_many :users, :class_name => "User", :through => :participations
  
  after_initialize :init
  
  def init
    self.verified ||= false
    self.admin ||= -1
  end
  
  
end

coMeeting/app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

	def index
    if params[:admin].blank?
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    else
      @meetings = Meeting.all
      respond_to do |format|
				format.html { render html: @meetings } # index.html.erb
			end
		end
	end


	def show
		@meeting = Meeting.find_by_token(params[:id])
		
		if @meeting.nil?
			@participation = Participation.find_by_token(params[:id])
			
			if !@participation.nil?
				@meeting = Meeting.find(@participation.meeting_id)
				@minutes = @meeting.minutes
				@static_minutes = create_static_minutes(@meeting)
				@is_admin = false
				
				if @meeting.admin != -1
					@admin = User.find(@meeting.admin)
				end
				
			end
		else
			if @meeting.admin != -1
				@admin = User.find(@meeting.admin)
				if @meeting.verified == false
					name = " " + t("by") +" " + get_name_from(@admin)
				
					@meeting.participations.each do |participation|
						UserMailer.email(participation.user.mail, t("email.participant.subject", :admin => name, :default => "You were invited#{name} to a meeting"), t("email.participant.body", :link => "#{ENV['HOST']}/#{params[:locale]}/meetings/#{participation.token}") ).deliver
					end
					@meeting.verified = true
					@meeting.save
				end
			end
			@static_minutes = create_static_minutes(@meeting)
			@is_admin = true
		end
		
		respond_to do |format|
			if @meeting.nil?
				flash[:error] = t("meeting.error.show", :default => "The meeting you're looking for doesn't exist!")
				format.html { redirect_to root_path }
			else
				format.html # show.html.erb
			end
		end
	end


	def new
		@meeting = Meeting.new
		time = Time.new
		@current_date = time.day.to_s + '/' + time.month.to_s + '/' + time.year.to_s

		respond_to do |format|
			format.html # new.html.erb
		end
	end


	def create
		params[:meeting][:topics].reject!( &:blank? )
		params[:participations].reject!( &:blank? )

		@meeting = Meeting.new(params[:meeting])
		@meeting.token = UUIDTools::UUID.random_create().to_s
		@meeting.timezone = ActiveSupport::TimeZone.zones_map[params[:timezone]].to_s

		respond_to do |format|
			if @meeting.save
				params[:participations].each do |email|
					user = User.find_or_create_by_mail(email)

          @meeting.participations.create(:user_id => user.id, :token => UUIDTools::UUID.random_create().to_s)
				end

				if params[:admin][:mail].empty?
					@meeting.participations.each do |participation|
						UserMailer.email(participation.user.mail, t("email.participant.subject", :admin => params[:admin][:name].empty? ? "" : " by "+ params[:admin][:name] ), t("email.participant.body", :link => "#{ENV['HOST']}/#{params[:locale]}/meetings/#{participation.token}")).deliver
					end
					
					format.html { redirect_to meeting_path(@meeting.token), notice: t("meeting.created.withoutauth", :default => "Meeting successfully created without email confirmation.") }
				else
					admin = User.find_by_mail(params[:admin][:mail])
					if admin.nil?
						admin = User.create(:mail => params[:admin][:mail], :name => params[:admin][:name])
					else
            admin.update_attribute(:name, params[:admin][:name])  
					end
					
					@meeting.admin = admin.id
					@meeting.save
					
					name = get_name_from(admin)
					
					UserMailer.email(params[:admin][:mail], t("email.admin.subject", :admin => name, :default => "#{name}, here's your meeting administration link"), "#{ENV['HOST']}/#{params[:locale]}/meetings/#{@meeting.token}").deliver
					format.html { redirect_to root_path, notice: t("meeting.created.withauth", :default => "Meeting successfully created. Please check your email to continue the creation process.") }
				end
			else
				format.html { render action: "new" }
			end
		end
	end


	def edit
		@meeting = Meeting.find_by_token(params[:id])

		if @meeting.nil?
			respond_to do |format|
				flash[:error] = t("meeting.error.show", :default => "The meeting you're looking for doesn't exist!")
				format.html { redirect_to root_path }
			end
		else
			@participations = @meeting.participations
			if @meeting.admin != -1
				@admin = User.find(@meeting.admin)
			end
			respond_to do |format|
				format.html # edit.html.erb
			end
		end
	end
    
    
	def update
    params[:meeting][:topics].reject!( &:blank? )
		params[:participations].reject!( &:blank? )
        
		@meeting = Meeting.find_by_token(params[:id])
		@meeting.timezone = ActiveSupport::TimeZone.zones_map[params[:timezone]].to_s
		
		@meeting.save
		meeting_updated = @meeting.update_attributes(params[:meeting])
		
		
		if @meeting.admin != -1
			admin = User.find(@meeting.admin)
			admin.name = params[:admin][:name]
			admin.save
			
			name = " " + t("by") +" " + get_name_from(admin)
		else
			name = ""
		end
	
		if meeting_updated	
			participations = @meeting.participations

			participations.each do |participation|
				unless params[:participations].include?(participation.user.mail)
					participation.destroy
				end
			end

			params[:participations].each do |email|
				user = User.find_or_create_by_mail(email)

				participation = participations.find_by_user_id(user.id)
				if participation.nil?
					participation = Participation.new(:meeting_id => @meeting.id, :user_id => user.id, :token => UUIDTools::UUID.random_create().to_s)
					if participation.save
						UserMailer.email(email, t("email.participant.subject", :admin => name, :default => "You were invited#{name} to a meeting"), t("email.participant.body", :link => "#{ENV['HOST']}/#{params[:locale]}/meetings/#{participation.token}")).deliver
					end
				end
			end
		end

		respond_to do |format|
			if meeting_updated
				format.html { redirect_to meeting_path(@meeting.token), notice: t("meeting.updated", :default => "Meeting successfully updated.") }
			else
				format.html { render action: "edit" }
			end
		end
	end


	def destroy
		meeting = Meeting.find_by_token(params[:id])

		if meeting.nil?
			respond_to do |format|
				flash[:error] = t("meeting.error.delete", :default => "The meeting you tried deleting doesn't exist!")
				format.html { redirect_to root_path }
			end
		else
			meeting.destroy
			respond_to do |format|
				format.html { redirect_to root_path, notice: t("meeting.deleted", :default => "Meeting successfully deleted.") }
			end
		end
	end

	def update_action_item
		participation = Participation.find_by_id(params[:id])

		participation.update_attributes(:action_item => params[:action_item], :deadline => params[:deadline])

		meeting = Meeting.find_by_id(participation.meeting_id)
				
		@static_minutes = create_static_minutes(meeting)

		respond_to do |format|
			format.js
		end
	end

  def update_minutes
    meeting = Meeting.find_by_token(params[:id])

		meeting.update_attribute(:minutes, params[:minutes])

    render :nothing => true
  end


  def get_minutes
		meeting = Meeting.find_by_token(params[:id])
		
		@static_minutes = create_static_minutes(meeting)
		
		@minutes = meeting.minutes
		
    respond_to do |format|
			format.js
		end
  end

	respond_to :js
	def get_admin_circles
		user = User.find_by_mail(params[:mail])

		@data = ""
		user.circles.each do |u|
			mail = User.find_by_id(u).mail
			if mail.include?(params[:term])
				@data = @data + mail.to_s
				@data = @data + ", "
			end
		end

		respond_with(@data)
	end


	def download_pdf
		meeting = Meeting.find_by_token(params[:id])

		static_minutes = create_static_minutes(meeting)

		my_file = "tmp/minutes_#{UUIDTools::UUID.random_create()}.pdf"

		Prawn::Document.generate(my_file) do
			text static_minutes + (meeting.minutes.nil? ? "" : "\n\n" + meeting.minutes)
		end

		send_file my_file
	end	
	
	protected
	def create_static_minutes(meeting)

		topics = ""
		participants = ""
		action_items = ""

		meeting.topics.each do |topic|
			topics += "- " + topic + "\n\t"
		end

		meeting.participations.each do |participation|
			if !participation.user.name.blank?
				participants += "- #{participation.user.name} (#{participation.user.mail})".ljust(60)
			else
				participants += "- #{participation.user.mail}".ljust(60)
			end
			
			if participation.is_attending == 1
				participants += " " + t("attending.attended")
			elsif participation.is_attending == 0
				participants += " " + t("attending.unanswered")
			elsif participation.is_attending == -1
				participants += " " + t("attending.not_attended")
			end
			participants += "\n\t"
			if !participation.action_item.nil? && !participation.deadline.nil? && !participation.action_item.empty? && !participation.deadline.empty?
				if !participation.user.name.empty?
					action_items += "\n\t- " + participation.user.name + " (" + participation.user.mail + ")" + " => " + participation.action_item.to_s + " " + t('until') + " " + participation.deadline.to_s
				else
					action_items += "\n\t- " + participation.user.mail + " => " + participation.action_item.to_s + " " + t('until') + " " + participation.deadline.to_s
				end
			end
		end
		
		minutes = "\n" + t("subject") + ": " + meeting.subject +
			"\n" + t("local") + ": " + meeting.local +
			"\n" + t("date") + ": " + meeting.meeting_date.to_s +
			"\n" + t("time") + ": " + meeting.meeting_time.strftime("%1Hh:%Mm").to_s + " " + meeting.timezone +
			"\n" + t("duration") + ": " + meeting.duration.strftime("%1Hh:%Mm").to_s +
			"\n" + t("extra_info") + ": " + meeting.extra_info
		
		if meeting.admin != -1
			admin = User.find(meeting.admin)
			minutes = minutes + "\n" + t("administrator_name") + ": " + admin.name + "\n" + t("administrator_email") + ": " + admin.mail
		end
		
		minutes = minutes +	
			"\n\n\t" + t("topics") + ":" +
			"\n\t" + topics +
			"\n\t" + t("participants") + ":" +
			"\n\t" + participants +
			"\n\t" + t("actions") + ":" + action_items
			
		return minutes
	end	
end

coMeeting/app/helpers/meetings_helper.rb
module MeetingsHelper
end

coMeeting/app/views/meetings/_minutes.html.erb
<% if @is_admin %>
	<%= text_area :minutes, nil, :id => 'minutes', :value => @meeting.minutes , :onclick => "_idleNow = true;" %>
<% else %>
	<%= text_area :minutes, nil, :id => 'minutes', :value => @minutes, :class => "autosize disabled", :disabled => true %>
<% end %>
<script>
	$('textarea#minutes').autoResize({
		maxHeight: 1000,
		minHeight: 50
	});
</script>

coMeeting/app/views/meetings/_static_minutes.html.erb
<%= text_area :static_minutes, nil, :id => "static_minutes", :value => @static_minutes, :class => "disabled", :disabled => true %>
<script>
$('textarea#static_minutes').autoResize({
		maxHeight: 1000,
		minHeight: 50
	});
</script>

	

coMeeting/app/views/meetings/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="active"><%= link_to "#{t("edit_meeting", :default => "Edit Meeting")}", edit_meeting_path %></li>
    </ul>
  </div>
  <div class="content">
    <p>
    <div class="inner">
      <link rel="stylesheet" href="/assets/datepicker.css" type="text/css" />
      <script type="text/javascript" src="/assets/datepicker.js"></script>
      <%= form_for @meeting, :url => meeting_path(@meeting.token), :html => { :class => :form } do |f| -%>
        <%= render :partial => "editform", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<script>
  $('#date').DatePicker({
    flat: true,
    format: 'd/m/Y',
    date: $('#meeting_date').val(),
    calendars: 1,
    onChange: function(formated, dates){
      $('#meeting_date').val(formated);
    }
  });
</script>

coMeeting/app/views/meetings/get_admin_circles.html.erb
<%= @data%>

coMeeting/app/views/meetings/get_minutes.js.erb
$("#partialstatic_minutes").html('<%= escape_javascript(render 'static_minutes') %>');
$("#partialminutes").html('<%= escape_javascript(render 'minutes') %>');

coMeeting/app/views/meetings/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("list", :default => "List")}", meetings_path  %></li>
      <li><%= link_to "#{t("meeting.new", :default => "New Meeting")}", new_meeting_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("meetings", :default => "Meetings")  %></h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.meeting.subject", :default => t("activerecord.labels.subject", :default => "Subject")) %>
          </th>
                    <th><%= t("created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @meetings.each do |meeting| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= meeting.id %>
          </td>
                    <td>
            <%= link_to meeting.subject, meeting_path(meeting.token) %>
          </td>
                    <td>
            <%= meeting.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("show", :default => "Show")}", meeting_path(meeting.token) %> |
            <%= link_to "#{t("edit", :default => "Edit")}", edit_meeting_path(meeting.token) %> |
            <%= link_to "#{t("delete", :default => "Delete")}", meeting_path(meeting.token), :method => :delete, :confirm => "#{t("confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

coMeeting/app/views/meetings/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
	  <li class="active"><a href="#"><%= t("meeting.new", :default => "New Meeting") %></a></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">
      <link rel="stylesheet" href="/assets/datepicker.css" type="text/css" />
      <script type="text/javascript" src="/assets/datepicker.js"></script>
	  <p />
      <%= form_for :meeting, :url => meetings_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "createform", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>


<script>
  $('#date').DatePicker({
    flat: true,
    format: 'd/m/Y',
    date: $('#meeting_date').val(),
    calendars: 1,
    onChange: function(formated, dates){
        $('#meeting_date').val(formated);
    }
  });
</script>

coMeeting/app/views/meetings/show.html.erb
<div class="space outer_center">
	<% if @is_admin %>
		
		<div class="buttons wat-cf">
			<%= link_to image_tag("/assets/icons/application_edit.png", :alt => "")+ " " + t("meeting.edit", :default=> "Edit"), edit_meeting_path(@meeting.token), :class => "button" %>
			<%= link_to image_tag("/assets/icons/cross.png", :alt => "") + " " + t("meeting.delete", :default => "Delete"), meeting_path(@meeting.token), :confirm => t('confirm', :default => 'Are you sure?'), :method => :delete, :class => "button" %>
		</div>
			
	<% else %>                                                   
	
		<% if @meeting.admin == -1 %>
			<p class="warning"><%= t("meeting.warning") %></p>
		<% end %>
		
		<div class="buttons wat-cf">
			<% if @participation.is_attending == 1 %>
				<span class="text_button_padding"><%= t("attending.confirm", :default=> "Attending") %> | </span>
			<% elsif @participation.is_attending == -1 %>
				<span class="link_button text_button_padding"><%= t("attending.decline", :default=> "Not Attending") %> | </span>
			<% end %>
			
			<% if @participation.is_attending == 0 || @participation.is_attending == -1 %>
			
				<%= link_to image_tag("/assets/icons/tick.png", :alt => "")+ " " + t("attending.confirm", :default=> "Attending"), confirm_participation_path(@participation.token), :class => "button" %>
					
			<% end %>
			
			<% if @participation.is_attending == 1 || @participation.is_attending == 0 %>
			
				<%= link_to image_tag("/assets/icons/cross.png", :alt => "")+ " " + t("attending.decline", :default=> "Not Attending"), decline_participation_path(@participation.token), :class => "button" %>
				
			<% end %>
		</div>
	<% end %>
</div>

<div class="block" id="block-info">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="active"><a href="#block-info"><%= t("info", :default => "Info") %></a></li>
      <li class="first"><a href="#block-topics"><%= t("topics", :default => "Topics") %></a></li>
      <li class="first"><a href="#block-participants"><%= t("participants", :default => "Participants") %></a></li>
      <li class="first"><a href="#block-act"><%= t("minutes", :default => "Minutes") %></a></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">
		<% if @meeting.admin != -1 %>
		  <% if @is_admin %>
			<p>
				<b> <%= t("form.name.label", :default => "Your name") %> :</b>
				<%= @admin.name %>
			</p>
			<p>
				<b> <%= t("form.email.label", :default => "Your email") %> :</b>
				<%= @admin.mail %>
			</p>
		  <% else %>
			<p>
				<b> <%= t("administrator_name", :default => "Administrator name") %> :</b>
				<%= @admin.name %>
			</p>
			<p>
				<b> <%= t("administrator_email", :default => "Administrator email") %> :</b>
				<%= @admin.mail %>
			</p>
		  <% end %>
		<% end %>
      <p>
        <b><%= t("form.subject", :default => "Subject") %> :</b>
          
        <%= @meeting.subject %>
      </p>

      <p>
        <b><%= t("form.place", :default => "Place") %> :</b>
        <%= @meeting.local %>
      </p>

      <p>
        <b><%= t("form.date", :default => "Date") %> :</b>
        <%= Date.parse(@meeting.meeting_date).to_formatted_s(:long) %>
      </p>

      <p>
        <b><%= t("form.time", :default => "Time") %> :</b>
        <%= @meeting.meeting_time.strftime("%1Hh:%Mm") %> <%= @meeting.timezone %>
      </p>

      <p>
        <b><%= t("form.duration", :default => "Duration") %> :</b>
        <%= @meeting.duration.strftime("%1Hh:%Mm") %>
      </p>
	
      <% unless @meeting.extra_info.blank? %>
			<b><%= t("form.extra_info", :default => "Extra info") %> :</b>
			<%= @meeting.extra_info %>
	  <% end %>
    </div>
  </div>
</div>

<div class="block" id="block-topics">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><a href="#block-info"><%= t("info", :default => "Info") %></a></li>
      <li class="active"><a href="#block-topics"><%= t("topics", :default => "Topics") %></a></li>
      <li class="first"><a href="#block-participants"><%= t("participants", :default => "Participants") %></a></li>
      <li class="first"><a href="#block-act"><%= t("minutes", :default => "Minutes") %></a></li>
    </ul>
  </div>

  <div class="content">
    <div class="inner">
      <table class="table">
        <% @meeting.topics.each do |topic| -%>
            <tr class="<%= cycle("odd", "even") %>">
              <td>
                <%= topic %>
              </td>
            </tr>
        <% end -%>
      </table>
    </div>
  </div>
</div>

<div class="block" id="block-participants">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><a href="#block-info"><%= t("info", :default => "Info") %></a></li>
      <li class="first"><a href="#block-topics"><%= t("topics", :default => "Topics") %></a></li>
      <li class="active"><a href="#block-participants"><%= t("participants", :default => "Participants") %></a></li>
      <li class="first"><a href="#block-act"><%= t("minutes", :default => "Minutes") %></a></li>
    </ul>
  </div>

  <div class="content">
    <div class="inner">
		<input type="hidden" id="token" value="<%=@meeting.token%>">
		<table class="centered table">
		
			<% if @is_admin %>
				<% if @meeting.participations.present? %>
					<tr>
						<td width='45%'><%= t("email.self", :default => "Email") %></td>
						<td width='25%'><%= t("status", :default => "Status") %></td>
						<td width='15%'><%= t("assign_action_item", :default => "Assign Action Item") %></td>
						<td width='15%'><%= t("send_email", :default => "Send Email") %></td>
					</tr>
					<% num = 0 %>
					<% @meeting.participations.each do |participation| %>
						<% rowClass = cycle("even", "odd") %>
						
						<tr class="<%=rowClass%>">
						  <td class="leftered" width='45%'>
							<% if participation.user.name.blank? %>
								<%=participation.user.mail %>
							<% else %>
								<%= participation.user.name %> (<%=participation.user.mail %>)
							<% end %>
						  </td>
						  
						  <% if participation.is_attending == -1 %>
							 <td width='25%'><%= t("attending.declined", :default => "This person is not attending") %></td>
							 <td width='15%'><a href="#" onclick="showAction('participant_<%=num%>'); return false;"><img src="/assets/icons/script.png" alt="<%= t("alt.add_minutes", :default => "Add action item to minutes")%>" /></a></td>
							 <td width='15%'></td>
						  <% elsif participation.is_attending == 0 %>
							 <td width='25%'><%= t("attending.unknown", :default => "This person has yet to answer") %></td>
							 <td width='15%'><a href="#" onclick="showAction('participant_<%=num%>');return false;"><img src="/assets/icons/script.png" alt="<%= t("alt.add_minutes", :default => "Add action item to minutes")%>" /></a></td>
							 <td width='15%'>
								<a id="email_image_<%= participation.id %>"href='#' onclick="sendEmail(<%= participation.id %>); return false;"><img src="/assets/icons/email.png"/></a>
							 </td>
						  <% elsif participation.is_attending == 1 %>
							<td width='25%'><%= t("attending.confirmed", :default => "This person is attending") %></td>
							<td width='15%'><a href="#" onclick="showAction('participant_<%=num%>');return false;"><img src="/assets/icons/script.png" alt="<%= t("alt.add_minutes", :default => "Add action item to minutes")%>" /></a></td>
							<td width='15%'></td>
						  <% end %>
						</tr>
						
						<tr id='participant_<%=num %>' class="hidden <%=rowClass%>">
							<td class="leftered" width='45%'><%= t("action", :default => "Action") %>: <input id='item' class="styled" type='text' maxlength='200' value='<%=participation.action_item%>' /></td>
							<td width='25%'><%= t("date", :default => "Date") %>: <input id='date' class="styled", type='text' maxlength='10' value='<%=participation.deadline%>'></td>
							<td class="centered" width='15%'><a href='#' onclick="addActionItem('participant_<%=num%>',<%=participation.id%>,'<%=participation.user.mail%>');return false;"><img src="/assets/icons/pencil.png" /></a></td>
							<td width='15%'></td>
						</tr>
						
						<% num = num + 1 %>
					<% end %>
				<% else %>
					<tr><td class="leftered"><%= t("meeting.no_participants", :default => "You still have not invited people to your meeting!") %></td></tr>
				<% end %>
			<% else %>
				<tr>
					<td width='65%'><%= t("email.self", :default => "Email") %></td>
					<td width='35%'><%= t("status", :default => "Status") %></td>
				</tr>
				<% if @meeting.participations.present? 
					num = 0 %>
					<% @meeting.participations.each do |participation| %>
						<% rowClass = cycle("even", "odd") %>
					
						<tr class="<%=rowClass%>">
							<td class="leftered" width='65%'><%=participation.user.mail %></td>
							<% if participation.is_attending == -1 %>
								<td width='35%'><%= t("attending.declined", :default => "This person is not attending") %></td>
							<% elsif participation.is_attending == 0 %>
								<td width='35%'><%= t("attending.unknown", :default => "This person has yet to answer") %></td>
							<% elsif participation.is_attending == 1 %>
								<td width='35%'><%= t("attending.confirmed", :default => "This person is attending") %></td>
							<% end %>
						</tr>
						<% num = num + 1 %>
					<% end %>
				<% end %>
			<% end %>
		</table>
    </div>
  </div>
</div>

<% if @is_admin || @participation.is_attending != 0 %>
<div class="block" id="block-act">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><a href="#block-info"><%= t("info", :default => "Info") %></a></li>
      <li class="first"><a href="#block-topics"><%= t("topics", :default => "Topics") %></a></li>
      <li class="first"><a href="#block-participants"><%= t("participants", :default => "Participants") %></a></li>
      <li class="active"><a href="#block-act"><%= t("minutes", :default => "Minutes") %></a></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner" id="partialstatic_minutes">
		<%= render :partial => 'static_minutes' %>
	</div>
	<div class="inner" id="partialminutes">
		<%= render :partial => 'minutes' %>
    </div>
  </div>
</div>

<div class="outer_center">
	<div class="buttons wat-cf">
		<%= link_to image_tag("/assets/icons/application_edit.png", :alt => "")+ " " + t("meeting.pdf", :default=> "Download as PDF"), download_pdf_path(@meeting.token), :class => "button" %>
	</div>
</div>
<% end %>

<script>
	<% if @is_admin %>
		_initMinutesListener();
	<% else %>
		setInterval("getMinutes('<%=@meeting.token%>')", 5000);
	<% end %>
	
	$('textarea').autoResize({
		maxHeight: 1000,
		minHeight: 50
	});
	
</script>

coMeeting/app/views/meetings/update_action_item.js.erb
$("#partialstatic_minutes").html('<%= escape_javascript(render 'static_minutes') %>');